# PodDar Config

# Options
dryrun: true # default is true to prevent unintentional executions

# PodConfigs
configs:
  path: "." # location of PodConfigs
  pods: [] # active PodConfigs, which aren't grouped
  groups: [] # active PodConfig groups

# Pods
pods:
  path: "/pods" # default path for pod data
