name: poddar
description: A simple application to handle pods in podman.
version: 1.0.0
repository: https://github.com/akjir/poddar/

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
